services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PRIVATE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PRIVATE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PRIVATE_POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project_network
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PRIVATE_PG_ADMIN}
      PGADMIN_DEFAULT_PASSWORD: ${PRIVATE_PG_ADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - project_network
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: my_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${PRIVATE_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${PRIVATE_MINIO_ROOT_PASSWORD}
    ports:
      - '9000:9000' # S3 API
      - '9001:9001' # MinIO web UI
    volumes:
      - minio_data:/data
    networks:
      - project_network

volumes:
  postgres_data:
  minio_data:

networks:
  project_network: